import argparse
import os
import random
from colorRange import colorFader, c1, c2

# CommonUtils.py acts as a helper function for PopulateStickies.py

# Keep track of used colors
colorFeatureMap = {}


# Read in stories from text file
# TODO: Eventually pull straight from wiki
def read_input():
    parser = argparse.ArgumentParser()
    parser.add_argument("wiki_files_directory",
                        help="Directory (folder) whose wiki files you want to convert to stickies")
    wiki_files_directory = parser.parse_args().wiki_files_directory

    storyList = []

    for filename in os.listdir(wiki_files_directory):
        file = open(wiki_files_directory + "/" + filename)
        lines = file.readlines()
        storyList += get_story_list(lines)
        file.close()
    return storyList, colorFeatureMap


# Inspired by https://stackoverflow.com/questions/28999287/generate-random-colors-rgb

def random_color():
    # TODO: Should we avoid choosing dark colors which obscure the text?
    red = random.randint(0, 255)
    green = random.randint(0, 255)
    blue = random.randint(0, 255)
    return "%02x%02x%02x" % (red, green, blue)


# Create a new method definition for selecting a color that will not obscure the text/title field
# Alternate option: Change text color to accommodate random colors

# Create a base selection of acceptable colors in a certain range of RGB values --> colorRange.py
# TODO: ADD random (numColors) colors (light colors only) to the array of acceptable colors
def select_Color_InRange():
    numColors = 25
    # Populate the colors list from a list of acceptable Colors, this list of acceptable colors was generated by
    # colorRange.py
    for i in numColors:
        colors = list(colorFader(c1, c2, mix=0))

    # The selector is the variable holding the index in the colors Array of the Color we will pick at Random. This color
    # list had been modified by colorRange.py
    selector = random.randint(0, len(colors))
    return colors(selector)


def get_story_list(lines):
    feature = lines[0].rstrip()
    projectColor = select_Color_InRange()  # This was changed from randomColor() to select_color_InRange

    # Make sure color is not a repeat from a different project
    while projectColor in colorFeatureMap:
        projectColor = select_Color_InRange()  # This was changed from randomColor() to select_color_InRange to
        # reflect feature update

    colorFeatureMap[projectColor] = feature

    # Parse stories from text file
    startIndex = 0
    for i in range(len(lines)):
        if "==Stories" in lines[i]:
            startIndex = i + 1
            break

    storyList = []
    storyCategory = ""
    for line in lines[startIndex: len(lines)]:
        if line.startswith("==="):
            stripAfter = line.find("(")
            storyCategory = line[3:stripAfter]
        elif line.startswith("* "):
            stripAfter = line.rfind("(")
            storyDescription = line[2:stripAfter]
            storySize = line[stripAfter + 1: line.rfind(")")]
            storyInfo = (storyCategory, storyDescription, [], storySize, feature, projectColor)
            storyList.append(storyInfo)
        elif line.startswith("**") and storyInfo:
            storyInfo[2].append(line[3:].rstrip())
        elif line.startswith("-") and storyInfo:  # The "-" sentinel value will serve as the parse indicator for
            # Acceptance Criteria
            storyInfo[3].append(line[4].rstrip())
    return storyList
